name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        django-version: ["4.2", "5.0", "5.1"]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        pip install coverage
        pip install codecov
        pip install "django==${{ matrix.django-version }}" --pre
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests
      run: |
        coverage run --source='.' manage.py test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
